sudo: required
services: docker
notifications:
  email: false

env:
  - PHP_VERSION=7.3
  - PHP_VERSION=7.2
  - PHP_VERSION=7.1
  - PHP_VERSION=5.6

cache:
  directories:
    - ${HOME}/.composer/cache

script:
  - make

after_success:
  - if [[ "${TRAVIS_BRANCH}" == "master" ]]; then
      docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD};
      make publish;
    fi
