sudo: required
services: docker
notifications:
  email:
    on_failure: always

branches:
  only:
  - master
  - develop

cache:
  directories:
  - ${HOME}/.composer/cache

before_script:
  - make vendor
  - mkdir build

script:
  - make build -j 10

after_success:
  - if [[ "${TRAVIS_BRANCH}" == "master" && "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
      docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_ACCESS_TOKEN};
      docker push worldpeaceio/wordpress-integration;
    fi
