sudo: required
services: docker
notifications:
  email:
    on_failure: always

branches:
  only:
  - master
  - develop

cache:
  directories:
  - ${HOME}/.composer/cache

env:
  - PHP_VERSION=7.4
  - PHP_VERSION=7.3
  - PHP_VERSION=7.2

before_script:
  - make composer_install

script:
  - make lint
  - make build_image
  - make test

after_success:
  - if [[ "${TRAVIS_BRANCH}" == "master" && "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
      docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_ACCESS_TOKEN};
      make publish;
    fi
