sudo: required
services: docker
notifications:
  email:
    on_failure: always

branches:
  only:
  - master
  - develop

cache:
  directories:
  - ${HOME}/.composer/cache

env:
  - PHP_VERSION=7.3
  - PHP_VERSION=7.2
  - PHP_VERSION=7.1

script:
  - make
