sudo: required
services: docker
notifications:
  email: false

env:
  - PHP_VERSION=7.2
  - PHP_VERSION=7.1
  - PHP_VERSION=7.0

cache:
  directories:
    - ${PHP_VERSION}/vendor

script:
  - make

after_success:
  - if [[ "${TRAVIS_BRANCH}" == "master" ]]; then
      docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD};
      make publish;
    fi
