sudo: required
services: docker
notifications:
  email: false

env:
  global:
    - IMAGE_NAME=nateinaction/wordpress-integration
  matrix:
    - PHP_VERSION=7.2
    - PHP_VERSION=7.1
    - PHP_VERSION=7.0

cache:
  directories:
    - PHP_7.2/vendor
    - PHP_7.1/vendor
    - PHP_7.0/vendor

script:
  - make

after_success:
  - if [[ "${TRAVIS_BRANCH}" == "master" ]]; then
      docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD};
      make publish;
    fi
