---
name: ci
on: push

jobs:
  lint:
    name: super-linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: super-linter
        uses: docker://github/super-linter:v3.12.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_BASH: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_PHP: true
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build
        run: make build -j 10
      - name: Deploy to DockerHub
        if: github.ref == 'refs/heads/master'
        run: |
          docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_TOKEN};
          docker push ${GITHUB_REPOSITORY};
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
