---
name: Deploy
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build
        run: make build -j 10
      - name: DockerHub Login
        run: docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_TOKEN};
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Deploy to DockerHub
        run: docker push ${GITHUB_REPOSITORY};
      - name: Sync README.md with DockerHub
        uses: peter-evans/dockerhub-description@v2.1.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_REPOSITORY: ${GITHUB_REPOSITORY}
