---
name: Lint
on:
  push:
    branches-ignore:
      - 'master'
jobs:
  lint:
    name: super-linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: super-linter
        uses: docker://github/super-linter:v3.12.0
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_BASH: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_PYTHON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_PHP: true
