---
# Build and publish images on WordPress version change
name: wp-version-change
on:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes
#    - cron: "30 */6 * * *" # every 6 hours

jobs:
  wp-version:
    name: Check WordPress Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Check version, commit, build and push to docker hub
        run: |
          # Check lastest WP version on wordpress.org
          curl -s "https://api.wordpress.org/core/version-check/1.7/" | jq -r '.offers[0].current' > wordpress_version.txt
          WORDPRESS_VERSION="$(cat wordpress_version.txt)"
          BRANCH_NAME="wp${WORDPRESS_VERSION}"
          # Compare latest with repo version
          if ! git diff --exit-code wordpress_version.txt; then
            # Setup git and github cli
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git remote set-url origin https://nateinaction:${GITHUB_TOKEN}@github.com/worldpeaceio/wordpress-integration.git
            echo $GITHUB_TOKEN | gh auth login --with-token
            # Check to see if a PR has already been made
            if ! gh pr checkout "${BRANCH_NAME}"; then
              # Update the readme
              make clean build -j 10
              # Create the branch
              git checkout -b "${BRANCH_NAME}"
              # Commit the changes
              COMMIT_MESSAGE="Update WordPress to $(cat wordpress_version.txt)"
              git commit -m "${COMMIT_MESSAGE}" -a
              # Push to github and create a PR
              git push origin "${BRANCH_NAME}"
              gh pr create --title "${COMMIT_MESSAGE}" --body "This PR was automatically generated by the wp-version-change Github Action"
            fi
          fi
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
