name: wp-version-change
on:
  schedule:
    - cron: "*/5 * * * *" # every 5 minutes

jobs:
  wp-version:
    name: Check WordPress Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Check version, commit, and build
        run: |
          mkdir -p build
          # Check lastest WP version on wordpress.org
          curl -s "https://api.wordpress.org/core/version-check/1.7/" | jq -r '.offers[0].current' > build/wordpress_version.txt
          # Compare latest with repo version, if they're different, commit the changes
          if ! diff build/wordpress_version.txt wordpress_version.txt; then
            mv build/wordpress_version.txt wordpress_version.txt
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -m "Update WordPress to $(cat wordpress_version.txt)" -a
            make clean build -j 10
          fi
      - name: Deploy to Docker Hub
        if: github.ref == 'refs/heads/master'
        run: |
          docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_TOKEN};
          docker push ${GITHUB_REPOSITORY};
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push changes to master
        uses: ad-m/github-push-action@master
        if: github.ref == 'refs/heads/master'
        with:
          # Using a repo's default token will not trigger the ci action
          # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
